DROP TABLE ITEM;

CREATE TABLE ITEM(ID BIGINT PRIMARY KEY AUTO_INCREMENT, ITEM_NUMBER VARCHAR(255), NAME VARCHAR(255), DESCRIPTION VARCHAR(255), AVAILABLE_QUANTITY INT, UNIT_PRICE BIGDECIMAL(20,2));

INSERT INTO ITEM (ITEM_NUMBER,NAME,DESCRIPTION,AVAILABLE_QUANTITY,UNIT_PRICE) VALUES('0001','Ray Ban','looks good',20,88.98);
INSERT INTO ITEM (ITEM_NUMBER,NAME,DESCRIPTION,AVAILABLE_QUANTITY,UNIT_PRICE) VALUES('0002','Levis','unexpensive',50,30);
INSERT INTO ITEM (ITEM_NUMBER,NAME,DESCRIPTION,AVAILABLE_QUANTITY,UNIT_PRICE) VALUES('0003','Gucci','good style',40,100);
INSERT INTO ITEM (ITEM_NUMBER,NAME,DESCRIPTION,AVAILABLE_QUANTITY,UNIT_PRICE) VALUES('0004','Prada','popular',23,200);
INSERT INTO ITEM (ITEM_NUMBER,NAME,DESCRIPTION,AVAILABLE_QUANTITY,UNIT_PRICE) VALUES('0005','Oakley','good quality',50,90);

CREATE TABLE 